services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fkt_alumni_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    networks:
      - fkt_alumni

  mysql:
    image: mysql:8.0
    container_name: fkt_alumni_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fkt_alumni
    command: ['mysqld']
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  fkt_alumni:
    driver: bridge

volumes:
  mysql_data:
    driver: local